name: borome
description: A new Flutter project.
version: 0.1.0

publish_to: "none"

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  injector: ^2.0.0
  shared_preferences: ^2.0.6
  package_info: '>=0.4.3 <2.0.0'
  intl: ^0.17.0
  flutter_scale_aware:
    git: https://github.com/jogboms/flutter_scale_aware.git
  provider: ^5.0.0
  uuid: ^3.0.4
  rxstore:
  flutter_rxstore:
  freezed_annotation:
  rxdart: ^0.26.0
  flutter_webview_plugin: ^0.4.0
  contacts_service: ^0.6.1
  permission_handler: ^6.1.3
  geolocator: ^7.0.3
  camera:
    git:
      url: git://github.com/jogboms/plugins.git
      path: packages/camera
  file_picker: ^3.0.2+2
  image_picker: ^0.8.0
  flutter_downloader: ^1.6.1
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^6.0.0
  cached_network_image: ^3.0.0
  local_auth: ^1.1.6
  logging: ^1.0.1
  flutter_cache_manager: ^3.1.0
  flutter_secure_storage: ^4.2.0
  reading_time: ^1.0.0+2
  clock: ^1.1.0
  faker: ^2.0.0
  fake_async: ^1.2.0
  platform: ^3.0.0
  http_extensions: ^1.0.0
  http_extensions_retry:
    git:
      url: http://github.com/jogboms/http_extensions.git
      path: http_extensions_retry
  http_extensions_log:
    git:
      url: http://github.com/jogboms/http_extensions.git
      path: http_extensions_log
  http_extensions_headers: ^1.0.0
  http_extensions_cache: ^1.0.0
  rating_dialog:
    git: https://github.com/jogboms/rating_dialog.git
  launch_review: ^3.0.1
  sentry: ^5.0.0
  device_info: ^2.0.2
  crypto: ^3.0.1
  built_value: ^8.0.6
  built_collection: ^5.0.0

dependency_overrides:
  http_extensions:
    git:
      url: http://github.com/jogboms/http_extensions.git
      ref: c44cea5c37b3f8a6b482fc6129d3f169fd95edea
      path: http_extensions
  analyzer: 1.7.0
  freezed: ^0.12.7
  freezed_annotation: ^0.12.0
  rxdart: ^0.26.0
  http: ^0.13.0
  meta: ^1.4.0
  test_api: ^0.2.19-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  mfsao: ^1.0.0
  mockito: ^4.1.4
  build_runner: ^1.10.3
  built_value_generator: ^8.0.6
  freezed:
  pedantic:
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
    - assets/onboard/
    - assets/image_icons/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 800

    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
