/// Flutter icons AppIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData email = IconData(0xf100, fontFamily: _kFontFam);
  static const IconData social = IconData(0xf101, fontFamily: _kFontFam);
  static const IconData right_arrow = IconData(0xf102, fontFamily: _kFontFam);
  static const IconData facebook = IconData(0xf103, fontFamily: _kFontFam);
  static const IconData twitter = IconData(0xf104, fontFamily: _kFontFam);
  static const IconData credit_card = IconData(0xf105, fontFamily: _kFontFam);
  static const IconData fingerprint = IconData(0xf106, fontFamily: _kFontFam);
  static const IconData wallet = IconData(0xf107, fontFamily: _kFontFam);
  static const IconData smartphone = IconData(0xf108, fontFamily: _kFontFam);
  static const IconData padlock = IconData(0xf109, fontFamily: _kFontFam);
  static const IconData left_arrow = IconData(0xf10a, fontFamily: _kFontFam);
  static const IconData photo_camera = IconData(0xf10b, fontFamily: _kFontFam);
  static const IconData calendar = IconData(0xf10c, fontFamily: _kFontFam);
  static const IconData down_arrow = IconData(0xf10d, fontFamily: _kFontFam);
  static const IconData instagram = IconData(0xf10e, fontFamily: _kFontFam);
  static const IconData check = IconData(0xf10f, fontFamily: _kFontFam);
  static const IconData cancel = IconData(0xf110, fontFamily: _kFontFam);
  static const IconData expand = IconData(0xf111, fontFamily: _kFontFam);
  static const IconData alarm = IconData(0xf112, fontFamily: _kFontFam);
  static const IconData bank = IconData(0xf113, fontFamily: _kFontFam);
  static const IconData earth_grid = IconData(0xf114, fontFamily: _kFontFam);
  static const IconData monitor = IconData(0xf115, fontFamily: _kFontFam);
  static const IconData thunderbolt = IconData(0xf116, fontFamily: _kFontFam);
  static const IconData home = IconData(0xf117, fontFamily: _kFontFam);
  static const IconData rotate = IconData(0xf118, fontFamily: _kFontFam);
  static const IconData percentage = IconData(0xf119, fontFamily: _kFontFam);
  static const IconData profit = IconData(0xf11a, fontFamily: _kFontFam);
  static const IconData chevron = IconData(0xf11b, fontFamily: _kFontFam);
  static const IconData filter = IconData(0xf11c, fontFamily: _kFontFam);
  static const IconData money = IconData(0xf11d, fontFamily: _kFontFam);
  static const IconData phone_book = IconData(0xf11e, fontFamily: _kFontFam);
  static const IconData folder = IconData(0xf11f, fontFamily: _kFontFam);
  static const IconData buildings = IconData(0xf120, fontFamily: _kFontFam);
  static const IconData id_card = IconData(0xf121, fontFamily: _kFontFam);
  static const IconData followers = IconData(0xf122, fontFamily: _kFontFam);
  static const IconData width = IconData(0xf123, fontFamily: _kFontFam);
  static const IconData chat = IconData(0xf124, fontFamily: _kFontFam);
  static const IconData file = IconData(0xf125, fontFamily: _kFontFam);
  static const IconData trash = IconData(0xf126, fontFamily: _kFontFam);
  static const IconData plus = IconData(0xf127, fontFamily: _kFontFam);
  static const IconData diskette = IconData(0xf128, fontFamily: _kFontFam);
  static const IconData add_file = IconData(0xf129, fontFamily: _kFontFam);
}
